services:
  - type: web
    name: shopy-bot
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8907545202:AAFH1we_J12zJhjDx1tCCZHddkLKT8x8naw
